### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by lukejanicke** [lgarron/folderify#34]
I tried both install methods. Used `sudo`. Tried on several test folders. Terminal always spits out the following. It’s beyond me. Not sure if it’s something I can fix or an issue with the code.

`````
~/Git/folderify $ sudo python -m folderify examples/src/folder_outline.png . --reveal
[.] <= [examples/src/folder_outline.png]
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/lukejanicke/Git/folderify/folderify/__main__.py", line 391, in <module>
    main()
  File "/Users/lukejanicke/Git/folderify/folderify/__main__.py", line 365, in main
    is_from_cache=False
  File "/Users/lukejanicke/Git/folderify/folderify/__main__.py", line 289, in create_and_set_icns
    processes = map(f, inputs[folder_type])
  File "/Users/lukejanicke/Git/folderify/folderify/__main__.py", line 179, in create_iconset
    TEMP_MASK_IMAGE
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
~/Git/folderify $ 
`````

**Comment by lgarron** [comment]
Hmm. Unfortunately, I can't reproduce this. :-(
My best guess is that `TEMP_MASK_IMAGE` is either incorrect, of that `temp_folder` is not created.

Could you add

    print("TEMP_MASK_IMAGE:", TEMP_MASK_IMAGE)

before `subprocess.check_call` on line 171, and add

    print("temp_folder:", temp_folder)

on the line after `temp_folder = tempfile.mkdtemp()` on line 39?

I get the following output:

    temp_folder: /var/folders/x2/zk6kswt94zx4cqw4l56cmhjh008dj1/T/tmpvsIi7X
    [.] <= [examples/src/folder_outline.png]
    TEMP_MASK_IMAGE: /var/folders/x2/zk6kswt94zx4cqw4l56cmhjh008dj1/T/tmpvsIi7X/trimmed_16x16.png
    TEMP_MASK_IMAGE: /var/folders/x2/zk6kswt94zx4cqw4l56cmhjh008dj1/T/tmpvsIi7X/trimmed_16x16@2x.png
    TEMP_MASK_IMAGE: /var/folders/x2/zk6kswt94zx4cqw4l56cmhjh008dj1/T/tmpvsIi7X/trimmed_32x32.png
    TEMP_MASK_IMAGE: /var/folders/x2/zk6kswt94zx4cqw4l56cmhjh008dj1/T/tmpvsIi7X/trimmed_32x32@2x.png
    TEMP_MASK_IMAGE: /var/folders/x2/zk6kswt94zx4cqw4l56cmhjh008dj1/T/tmpvsIi7X/trimmed_128x128.png
    TEMP_MASK_IMAGE: /var/folders/x2/zk6kswt94zx4cqw4l56cmhjh008dj1/T/tmpvsIi7X/trimmed_128x128@2x.png
    TEMP_MASK_IMAGE: /var/folders/x2/zk6kswt94zx4cqw4l56cmhjh008dj1/T/tmpvsIi7X/trimmed_256x256.png
    TEMP_MASK_IMAGE: /var/folders/x2/zk6kswt94zx4cqw4l56cmhjh008dj1/T/tmpvsIi7X/trimmed_256x256@2x.png
    TEMP_MASK_IMAGE: /var/folders/x2/zk6kswt94zx4cqw4l56cmhjh008dj1/T/tmpvsIi7X/trimmed_512x512.png
    TEMP_MASK_IMAGE: /var/folders/x2/zk6kswt94zx4cqw4l56cmhjh008dj1/T/tmpvsIi7X/trimmed_512x512@2x.png

Could you check that:
1) `temp_folder` has a sensible path,
2) the folder is actually created by `tempfile.mkdtemp()`, and
3) the correct value for the created folder is passed to `create_iconset`?

**Comment by lukejanicke** [comment]
I added those two lines.
Though, I found `temp_folder = tempfile.mkdtemp()` on line 235 (236 after adding the first extra line).

Output:

`````
~/git/folderify $ python -m folderify examples/src/folder_outline.png . --reveal
temp_folder: /var/folders/g4/qw8ykb5j77g9ghs3cyz105q80000gn/T/tmp6VTfnJ
[.] <= [examples/src/folder_outline.png]
TEMP_MASK_IMAGE: /var/folders/g4/qw8ykb5j77g9ghs3cyz105q80000gn/T/tmp6VTfnJ/trimmed_16x16.png
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/lukejanicke/Git/folderify/folderify/__main__.py", line 393, in <module>
    main()
  File "/Users/lukejanicke/Git/folderify/folderify/__main__.py", line 367, in main
    is_from_cache=False
  File "/Users/lukejanicke/Git/folderify/folderify/__main__.py", line 291, in create_and_set_icns
    processes = map(f, inputs[folder_type])
  File "/Users/lukejanicke/Git/folderify/folderify/__main__.py", line 180, in create_iconset
    TEMP_MASK_IMAGE
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
~/git/folderify $ 
`````

**Comment by lukejanicke** [comment]
Installing via pip.

`````
~ $ sudo pip install folderify
Password:
The directory '/Users/lukejanicke/Library/Logs/pip' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/Users/lukejanicke/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/Users/lukejanicke/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
Collecting folderify
  Downloading folderify-1.0.0.tar.gz (3.1MB)
    100% |################################| 3.1MB 62kB/s 
Installing collected packages: folderify
  Running setup.py install for folderify
    Installing folderify script to /usr/local/bin
Successfully installed folderify-1.0.0
`````

There’s a message in there about directory permissions and owner.

I tried with a `-H` flag, which was invalid.

So, I used lowercase `-h` and it just output the help.

`````
sudo folderify -h projects.png .
~/Projects $ sudo folderify -h projects.png .
usage: folderify [-h] [--reveal] [--osx VERSION] [--cache] [--cache-dir DIR]
                 [--cache-list] [--cache-restore PATH] [--cache-restore-all]
                 [--cache-remove PATH] [--verbose]
                 [mask] [target]

...
`````

**Comment by lgarron** [comment]
Did `/var/folders/g4/qw8ykb5j77g9ghs3cyz105q80000gn/T/tmp6VTfnJ` actually get created on your system?

**Comment by lukejanicke** [comment]
`````
~ $ cd /var/folders/g4/qw8ykb5j77g9ghs3cyz105q80000gn/T/tmp6VTfnJ
/var/folders/g4/qw8ykb5j77g9ghs3cyz105q80000gn/T/tmp6VTfnJ $ ls -all
total 0
drwx------    3 lukejanicke  staff   102 24 Feb 17:43 .
drwx------  272 lukejanicke  staff  9248 24 Feb 18:16 ..
drwxr-xr-x    2 lukejanicke  staff    68 24 Feb 17:43 iconset.iconset
/var/folders/g4/qw8ykb5j77g9ghs3cyz105q80000gn/T/tmp6VTfnJ $ 
`````

Seems so.

**Comment by lukejanicke** [comment]
I removed the git installed version and am just running the pip installed version now. Not sure if that would have caused any conflicts.

**Comment by zchee** [comment]
+1

```
  File "/usr/local/bin/folderify", line 9, in <module>
    load_entry_point('folderify==1.0.0', 'console_scripts', 'folderify')()
  File "/usr/local/lib/python2.7/site-packages/folderify/__main__.py", line 365, in main
    is_from_cache=False
  File "/usr/local/lib/python2.7/site-packages/folderify/__main__.py", line 289, in create_and_set_icns
    processes = map(f, inputs[folder_type])
  File "/usr/local/lib/python2.7/site-packages/folderify/__main__.py", line 179, in create_iconset
    TEMP_MASK_IMAGE
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by stnvh** [comment]
You're missing imagemagick, install using brew: ```brew install imagemagick```.

Always read the README! Dependencies are important.

**Comment by lgarron** [comment]
Thanks for finding the issue, @stnvh!

That's not obvious at all, and software should be friendly. I'll try to mention ImageMagick at the beginning of the instructions, and give a warning if the code fails.

**Comment by lgarron** [comment]
@lukejanicke and @zchee: Could you run `pip install --upgrade folderify` (or `git pull`) and try again?
