### ISSUE TITLE
`seticon` seems to be incompatible with 10.15.3

### ISSUE THREAD

**Issue by dreki** [lgarron/folderify#40]
`folderify` is a fun tool and I'd love to keep using it. Thanks for making it!

At some point since the last time I used `folderify` (in the last 4-6 months), something broke. Specifically, when running `folderify` now, I get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/folderify", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/folderify/__main__.py", line 374, in main
    is_from_cache=False
  File "/usr/local/lib/python3.7/site-packages/folderify/__main__.py", line 326, in create_and_set_icns
    target
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 86] Bad CPU type in executable: '/usr/local/lib/python3.7/site-packages/folderify/lib/seticon'
```

**Comment by llity** [comment]
I get this error too.

**Comment by lgarron** [comment]
Should be fixed in https://pypi.org/project/folderify/1.2.3/ !

**Comment by lgarron** [comment]
Should be fixed in https://pypi.org/project/folderify/1.2.3/ !

Thanks to @sveinbjornt for the 64-bit update!
